In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

## digits dataset in sklearn

In [5]:
digits=load_digits()

In [6]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [10]:
df_data=pd.DataFrame(digits.data)
df_data

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [12]:
df_target=pd.DataFrame(digits.target)
df_target

      0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [15]:
from sklearn.svm import SVC
model=SVC()

In [28]:
x=df_data
y=df_target

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [39]:
model.fit(x_train,y_train.values.ravel())

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
model.predict(x_test)

array([2, 0, 6, 4, 8, 2, 4, 0, 6, 4, 5, 6, 8, 3, 4, 3, 1, 7, 2, 0, 1, 8,
       1, 0, 1, 9, 8, 6, 1, 9, 1, 3, 4, 1, 2, 0, 1, 1, 4, 9, 9, 5, 4, 7,
       5, 6, 0, 8, 6, 9, 4, 7, 9, 6, 9, 6, 4, 9, 6, 7, 8, 4, 0, 6, 4, 4,
       9, 7, 3, 4, 0, 8, 6, 1, 9, 7, 4, 0, 2, 7, 9, 2, 3, 0, 5, 8, 5, 8,
       0, 5, 4, 8, 2, 4, 5, 0, 1, 5, 7, 1, 2, 6, 5, 4, 1, 3, 2, 3, 0, 4,
       7, 2, 0, 0, 9, 3, 0, 7, 7, 6, 1, 7, 2, 9, 8, 5, 6, 9, 4, 5, 2, 1,
       9, 5, 4, 8, 6, 5, 5, 1, 2, 2, 7, 5, 3, 6, 7, 6, 4, 7, 1, 0, 7, 7,
       4, 7, 4, 5, 3, 5, 9, 2, 0, 3, 5, 4, 4, 4, 1, 5, 2, 4, 1, 4, 7, 0,
       4, 8, 1, 8, 6, 9, 5, 1, 5, 5, 7, 8, 1, 9, 8, 4, 0, 9, 1, 8, 7, 6,
       3, 3, 3, 8, 2, 8, 7, 2, 9, 1, 9, 5, 8, 8, 9, 1, 6, 3, 3, 3, 1, 6,
       0, 4, 1, 3, 7, 3, 3, 8, 7, 4, 7, 8, 6, 4, 6, 6, 7, 5, 0, 9, 8, 8,
       5, 1, 2, 0, 3, 0, 9, 5, 8, 2, 1, 9, 7, 1, 3, 2, 3, 3, 1, 7, 9, 1,
       5, 2, 1, 5, 8, 7, 6, 4, 6, 4, 1, 9, 3, 4, 9, 9, 2, 5, 7, 0, 8, 1,
       6, 8, 9, 8, 0, 3, 6, 5, 6, 0, 4, 8, 4, 2, 8, 7, 9, 8, 2, 5, 3, 9,
       8, 2, 0, 1, 7, 7, 9, 2, 6, 4, 2, 1, 9, 0, 1, 6, 1, 3, 1, 4, 6, 0,
       1, 8, 8, 3, 4, 2, 1, 0, 0, 4, 7, 0, 9, 3, 8, 2, 2, 6, 2, 1, 8, 5,
       9, 9, 9, 0, 6, 7, 0, 0])

## Accuracy of model

In [41]:
model.score(x_test,y_test)

0.9861111111111112